[workspace]
members = [
    "01_hello",
    "02_echor",
    "02_echord",
    "03_catr",
    "03_catrd",
    "04_headr",
    "04_headrd",
    "05_wcr",
    "05_wcrd",
    "06_uniqr",
    "06_uniqrd",
    "07_findr",
]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.2", features = ["derive"] }
walkdir = "2.5.0"
regex = "1.10.4"

assert_cmd = "2.0.14"
predicates = "3.1.0"
rand = "0.8.5"
tempfile = "3.10.1"
